# Generated by Django 2.0 on 2020-04-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamilmatrimony', '0003_auto_20200409_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='mobile_no',
            field=models.IntegerField(default=1234567890),
        ),
    ]
