# Generated by Django 2.0 on 2020-04-11 21:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamilmatrimony', '0004_profiles_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='mobile_no',
            field=models.IntegerField(default=1234567890, validators=[django.core.validators.MinValueValidator(1000000000), django.core.validators.MaxValueValidator(9999999999)]),
        ),
    ]
