# Generated by Django 2.0 on 2020-04-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tamilmatrimony', '0005_auto_20200411_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
